=== TuWei1992/taobao-in-action/taobao-open-core/src/test/java/com/dream/messaging/config/fix/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by anders -->
<!--W3C Schema generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<!-- version="1.0" -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="message">
		<xs:complexType>
			<xs:sequence maxOccurs="1">
				<xs:element name="request" type="MsgType"
					minOccurs="0" maxOccurs="1"/>
				<xs:element name="response" type="MsgType"
					minOccurs="0" maxOccurs="1"/>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="propertyType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="section" type="SectionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
			</xs:sequence>
			
			<xs:attribute name="transcode" type="xs:string" use="required"/>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
			<xs:attribute name="version" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="SectionType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="propertyType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="section" type="SectionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="class" type="xs:string" use="optional"/>
		<xs:attribute name="status" use="optional" default="O">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="C"/>
					<xs:enumeration value="O"/>
					<xs:enumeration value="M"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="repeated" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="mapcount" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="max" type="xs:int" use="optional"/>
		<xs:attribute name="precondition" type="xs:string" use="optional"/>
		<xs:attribute name="delimiter" type="xs:string" use="optional"/>
		<xs:attribute name="suffix" type="xs:string" use="optional"/>
		<xs:attribute name="condition" type="xs:string" use="optional"/>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="setcondition" type="xs:string" use="optional"/>
		<xs:attribute name="resetcondition" type="xs:string" use="optional" />
		<xs:attribute name="desc" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:sequence>
					</xs:sequence>
		<xs:attribute name="format" type="xs:string" use="optional" />
		<xs:attribute name="status" use="optional" default="O">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="C" />
					<xs:enumeration value="O" />
					<xs:enumeration value="M" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="fixed" type="xs:string" use="optional" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="validvalue" type="xs:string" use="optional" />
		<xs:attribute name="default" type="xs:string" use="optional" />
		<xs:attribute name="condition" type="xs:string" use="optional" />
		<xs:attribute name="setcondition" type="xs:string"
			use="optional" />
		<xs:attribute name="resetcondition" type="xs:string"
			use="optional" />
		<xs:attribute name="class" type="xs:string" use="optional" />
		<xs:attribute name="reference" type="xs:string" use="optional" />
		<xs:attribute name="desc" type="xs:string" use="optional" />
		<xs:attribute name="length" type="xs:int" use="optional" />
		<xs:attribute name="countvalue" type="xs:string" use="optional" />
		<xs:attribute name="precondition" type="xs:string" use="optional" />
		<xs:attribute name="reqfield" type="xs:string" use="optional" />
	</xs:complexType>
    <xs:complexType name="MsgType">
    	<xs:choice maxOccurs="unbounded">
				<xs:element name="section" type="SectionType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="property" type="propertyType"
					minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="class" type="xs:string" use="required"/>
		<xs:attribute name="desc" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== TuWei1992/taobao-in-action/taobao-open-core/src/test/java/com/dream/messaging/config/fix/209813.xml
<?xml version="1.0" encoding="UTF-8"?>
<message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    version="1.0" transcode="209813" xsi:noNamespaceSchemaLocation="message.xsd" desc="积分查询(209813)">
    <request class="com.dream.messaging.connector.TIA209813">
        <property name="tia" reference="TIA_V1.0" />
        <property name="chanelFlag" class="string" length="1" status="M" default="C" /><!-- 渠道标记   X(1)    0=柜面、1=电话银行、2=网银、3=ATM、4=POS、5=多媒体终端、6=手机银行、7=家易通、9=财管平台（低柜）、L=第三方系统、Z=客服整合平台、W=IVR、V=卡中心兑换系统、S=卡中心收费系统、P=策略收单系统 -->
        <property name="idType" class="string" length="1" status="M" default="0" /><!-- 证件类型    X(1)    0-贷记卡号，1-清算账号ID -->
        <property name="id" class="string" length="28" status="M" /><!-- 证件号 X(28)   左对齐、右补空格 -->
        <property name="currencyType" class="string" length="3" /><!-- 币种  X(3)    CNY/USD；当证件类型为0时，若该字段为空则查询人民币和美元的积分余额     -->
    </request>
    <response class="com.dream.messaging.connector.TOA209813">
        <property name="toa" reference="TOA_V1.0" />
        <section precondition="outPutMessageType=N" repeated="false">
            <property name="totalMessageLength" class="int" length="4" status="M" /> <!-- 输出数据实际总长度   9(4)    整个数据区长度，包括本字段4字节在内 -->
            <property name="formatCode" class="string" length="5" status="M" /><!-- 五位格式码   X(5)    20H81 -->
            <property name="scoreBalanceCNY" class="int" length="8" status="M" /><!-- 积分余额(人民币)   9(8)    -->
            <property name="scoreBalanceUSD" class="int" length="8" status="M" /><!-- 积分余额(美元)    9(8)     -->
        </section>
         <section precondition="outPutMessageType=E" repeated="false">
            <property name="totalMessageLength" class="int" length="4" status="M" /><!-- 输出数据实际总长度   9(4)    整个数据区长度，包括本字段4字节在内 -->
            <property name="formatCode" class="string" length="5" status="M" /><!-- 五位格式码   X(5)    SCD04 -->
            <property name="errorAppCode" class="string" length="2" status="M" /><!-- 错误码所属应用符    X(2)     -->
            <property name="errorCode" class="int" length="4" status="M" /><!-- 错误信息码   9(4)     -->
            <property name="cursPos" class="int" length="4" status="M" /><!-- CURS-POS    9(4)    0001 -->
            <property name="errorMessage" class="string" length="56" /><!-- 错误信息    X(56)    -->
        </section>
    </response>
</message>

=== TuWei1992/taobao-in-action/taobao-open-core/src/test/java/com/dream/messaging/config/fix/TOA.xml
<message version="1.0" transcode="TOA" class="com.dream.messaging.connector.TOA"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="message.xsd" desc="响应报文头">
	<property name="CICSHeader" class="string" length="3"/><!--CICS功能信息头	X(3)-->
	<property name="outPutMessageType" class="string" length="1" setcondition="outPutMessageType"/><!--输出信息类型（N/A/E）	X(1)	执行结果类型 N＝正常，A＝需授权，E＝错误，Ｃ＝待复核确认。-->
	<property name="applicationType" class="string" length="2" /><!--信息码所属应用符	X(2)	必填（错误码前两位）-->
	<property name="infomationCode" class="int" length="4" /><!--信息码	9(4)	必填（错误码后四位）-->
	<property name="position" class="int" length="4" /><!--出错栏位光标位置	9(4)	多页查询时，如果没有下一页数据则此域填“6402”-->
	<property name="terminalNo" class="string" length="7" /><!--终端号（inHost）	X(7)	-->
	<property name="terminalSN" class="string" length="6" /><!--终端序列号（fromWorkstation）	9(6)	-->
	<property name="followingTranCode" class="int" length="4" /><!--后继交易码	9(4)	-->
	<property name="followingAppCode" class="int" length="2" /><!--后继交易的应用码	9(02)		-->
	<property name="tranFlag" class="string" length="3" /><!--交易符	X(3)			-->
	<property name="tranDate" class="int" length="8" /><!--交易日期	9(8)				-->
	<property name="tranTime" class="int" length="6" /><!--交易时间	9(6)				-->
	<property name="accountingDate" class="int" length="8" /><!--会计日期	9(8)					-->
	<property name="tranLogNo" class="int" length="9" /><!--交易日志号	9(9)						-->
	<property name="counterNo" class="string" length="7" /><!--柜员号	X(7)					-->
	<property name="seqNo" class="string" length="4" /><!--顺序号	9(4)					-->
	<property name="pageFlag" class="int" length="1" /><!--多页/印鉴输出标志（0/1/2）	9(1)						-->
	<property name="dataCompressedFlag" class="int" length="1" /><!--数据压缩标志（0/1）	9(1)							-->
	<property name="dataEncryptedFlag" class="int" length="1" /><!--数据加密标志（0/1）	9(1)							-->
	<property name="tranOrgCode" class="int" length="6" /><!--交易网点号	9(6)							-->
	<property name="authLog" class="string" length="1" /><!--授权LOG	X(1)							-->
	<property name="billFlag" class="string" length="1" /><!--金融传票标志	X(1)						-->
	<property name="authLevel" class="int" length="2" /><!--授权级别 9(2)							-->
	<property name="manager1" class="string" length="7" /><!--授权主管1	X(7)							-->
	<property name="manager2" class="string" length="7" /><!--授权主管2	X(7)						-->
	<property name="unused" class="string" length="5" /><!--	无效字段	X(5)						-->
	<property name="totalLength" class="int" length="4" /><!--	数据总长度	9(4)	长度包含自身字段的4字节长度在内。						-->
</message>

=== TuWei1992/taobao-in-action/taobao-open-core/src/test/java/com/dream/messaging/config/fix/TIA.xml
<message version="1.0" transcode="TIA" class="com.dream.messaging.connector.TIA"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="message.xsd" desc="请求报文头">
	<!-- 1000209813209813                           PCCCLUBT00                          00                                                             000000000003159970           C0123456                          -->
	<property name="CICSTranCode" class="string" length="4" status="M" /><!--CICS交易码	X(4)	-->
	<property name="appCode" class="int" length="2" status="M" /><!--应用码	9(2)	必填（交易码前两位， 如果交易码是209813，这里就填20）	-->
	<property name="tranCode" class="int" length="4" status="M" /><!--交易码	9(4)	必填（交易码后四位，如果交易码是209813，这里就填9813）-->
	<property name="frontEndTranCode" class="int" length="6" status="M" /><!--前置交易码	9(6)	必填（这个就是交易码）-->
	<property name="terminalSN" class="string" length="7"  /><!--终端序列号	X(7)	-->
	<property name="tranSource" class="string" length="5" /><!--交易来源	X(5)-->
	<property name="frontEndSN" class="string" length="15" /><!--前置流水号	X(15)-->
	<property name="counterNo" class="string" length="7" status="M" default="PCCCLUB" /><!--柜员号	X(7)	交易发起柜员号码(必填)（这里填操作员编号，即是谁发起了这笔交易）-->
	<property name="requestType" class="string" length="1" default="T" /><!--请求类型	X(1)	T＝原始交易；P＝请求下一页输出(必填)-->
	<property name="authLevel" class="int" length="2" default="00" /><!--授权级别	9(2)	-->
	<property name="manager1" class="string" length="7" /><!--主管1	X(7)	-->
	<property name="manager2" class="string" length="7" /><!--主管2	X(7)	-->
	<property name="managerPwd1" class="string" length="6" /><!--主管1的密码	X(6)	-->
	<property name="managerPwd2" class="string" length="6" /><!--主管1的密码	X(6)	-->
	<property name="managerPwdInput1" class="int" length="1" default="0" /><!--主管1的密码输入设备	9(1)		-->
	<property name="managerPwdInput2" class="int" length="1" default="0" /><!--主管2的密码输入设备	9(1)			-->
	<property name="authCode1" class="string" length="6" /><!--授权原因码1	X(6)				-->
	<property name="authCode2" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode3" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode4" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode5" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode6" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode7" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode8" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode9" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authCode10" class="string" length="6" /><!--授权原因码2	X(6)				-->
	<property name="authLogFlag" class="string" length="1" /><!--授权LOG标志(L/ )	X(1)			-->
	<property name="lastTranLogNo" class="int" length="9" default="000000000" /><!--最后一笔交易日志号	X(9)			-->
	<property name="dataCompressedFlag" class="int" length="1" default="0" /><!--数据压缩标志(0/1)	9(1)				-->
	<property name="dataEncryptedFlag" class="int" length="1" default="0"/><!--数据加密标志(0/1)	9(1)				-->
	<property name="tranOrgCode" class="int" length="6" status="M" default="315997"/><!--交易机构号(前置专用)	9(6)	必填（这里都填写为001997即可）				-->
	<property name="counterLevel" class="int" length="1" default="0" /><!--柜员级别(前置专用)	9(1)					-->
	<property name="terminalVersion" class="int" length="8" /><!--终端版本号	9(8)-->
	<property name="realCounter" class="string" length="1" /><!--外挂系统真实柜员	X(1)	-->
	<property name="TIAFilter" class="string" length="2" /><!--TIA-FILLER(CICS交易码)	X(2)-->
</message>
